name: Build and Push Docker Image
 
on:
  push:
    branches: [main]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Login to Docker image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mernecommers:latest .
 
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mernecommers:latest
 
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 15
 
    steps:
      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # Stop the container
            sudo docker stop combined ${{ secrets.DOCKER_USERNAME }} || true
 
            # Remove the container
            sudo docker rm combined ${{ secrets.DOCKER_USERNAME }} || true
 
            # Remove the Docker image
            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/mernecommers:latest || true
 
            # Pull the latest version of the Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mernecommers:latest
 
            # Run a new container
            sudo docker run -d -p 8000:8000 -p 8001:8001 --name combined ${{ secrets.DOCKER_USERNAME }}/mernecommers:latest
